/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petugas;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tubes.About;
import tubes.Login;
import tubes.Petugas;
import tubes.koneksi;

/**
 *
 * @author ggr
 */
public class Pembelian extends javax.swing.JFrame {
Connection con = koneksi.getConnection();
private Dimension dmn = Toolkit.getDefaultToolkit().getScreenSize();

    /**
     * Creates new form Pembelian
     */
    public Pembelian() {
        initComponents();
        aidi();
        tgl();
        this.setTitle("Apotek");
        this.setLocation(dmn.width/2-this.getWidth()/2,dmn.height/2-this.getHeight()/2 );
        
        id.setEnabled(false);
        tgl.setEnabled(false);
    }
    public void aidi(){
         try{
            String sql = "select max(right(IDBarang,3)) from barang";
            Statement stat = con.createStatement();
            ResultSet rs= stat.executeQuery(sql);
            while(rs.next()){
                if(rs.first()==false){
                    id.setText("BRG001");
                } else {
                    rs.last();
                    int aut = rs.getInt(1) + 1;
                        String nomor = String.valueOf(aut);
                        int Long = nomor.length();
                        
                        for(int a=0;a<3-Long;a++){
                            nomor = "0" + nomor;
                        }
                        id.setText("BRG"+nomor);
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "data gagal otomatis"+e);
        }

    }
    
    public void tgl(){
        Date skrg= new Date();
        SimpleDateFormat format= new SimpleDateFormat("dd MMMM yyyy");
        tgl.setText(format.format(skrg));
    }
    
    private void kosong(){
        nama.setText("");
        jns.setSelectedItem("Resep");
        hrg.setText("");
        jml.setText("");
        pmsk.setText("");
        ket.setText("");
        almt.setText("");
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tgl = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        almt = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        pmsk = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hrg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jml = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ket = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jns = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));
        getContentPane().add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 150, 30));

        jLabel11.setText("Tanggal:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, 30));

        almt.setColumns(20);
        almt.setRows(5);
        getContentPane().add(almt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 150, 90));

        jLabel10.setText("Alamat:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, 30));
        getContentPane().add(pmsk, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 150, 30));

        jLabel9.setText("Pemasok:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, 30));
        getContentPane().add(hrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 150, 30));

        jLabel8.setText("Harga:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 30));
        getContentPane().add(jml, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 150, 30));

        jLabel7.setText("Jumlah Barang:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 30));
        getContentPane().add(ket, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 150, 30));

        jLabel6.setText("Keterangan:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 30));

        jns.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Resep", "NonResep" }));
        getContentPane().add(jns, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 150, 30));

        jLabel5.setText("Jenis Barang:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 150, 30));

        jLabel4.setText("Nama Barang:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, 30));

        jLabel3.setText("ID Barang:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Penambahan Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/logo3.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/button_previous_01.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/90580cca18c50e5.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 350));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Keluar");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tentang");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MenuSelected

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        About about = new About();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(nama.getText().equals("") && hrg.getText().equals("") && ket.getText().equals("") && jml.getText().equals("") && pmsk.getText().equals("") && almt.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Data tidak boleh kosong !");
        }else{
        Connection con = koneksi.getConnection();
        String sql = "insert into pemasok values (?,?,?,?,?)";
        try {
            PreparedStatement stat = con.prepareStatement(sql);
            stat.setString(1, pmsk.getText());
            stat.setString(2, almt.getText());
            stat.setString(3, nama.getText());
            stat.setString(4, jml.getText());
            stat.setString(5, tgl.getText());
            stat.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" +e);
        }
        String sqll = "insert into barang values (?,?,?,?,?,?)";
        String name = "select * from barang where Nama='"+nama.getText()+"'";
        try {
            PreparedStatement stat = con.prepareStatement(sqll);
            ResultSet rs= stat.executeQuery(name);
            if(rs.first()==false){
                    stat.setString(1, id.getText());
                    stat.setString(2, nama.getText());
                    stat.setString(3, (String) jns.getSelectedItem());
                    stat.setString(4, hrg.getText());
                    stat.setString(5, jml.getText());
                    stat.setString(6, ket.getText());
                    stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Sudah Disimpan");
            } else {
                JOptionPane.showMessageDialog(null, "Stok Sudah Ditambahkan");
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" +e);
        }

        kosong();
        aidi();
        tgl();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Petugas ptg = new Petugas();
        ptg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea almt;
    private javax.swing.JTextField hrg;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jml;
    private javax.swing.JComboBox jns;
    private javax.swing.JTextField ket;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField pmsk;
    private javax.swing.JTextField tgl;
    // End of variables declaration//GEN-END:variables
}
