/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petugas;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tubes.About;
import tubes.JavaTerbilang;
import tubes.Login;
import tubes.koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author ggr
 */
public class Transaksi extends javax.swing.JFrame {
Connection con = koneksi.getConnection();
private Dimension dmn = Toolkit.getDefaultToolkit().getScreenSize();

int baris = 0;
   // Statement stt,stt2;
   // ResultSet rs,rss;
static Object kolom[] = {
  "ID Transaksi","Nama","Jumlah","Total"
};
 DefaultTableModel tabMode = new  DefaultTableModel(kolom,baris);

    /**
     * Creates new form NonResep
     */
    public Transaksi() {
        initComponents();
        aidi();
        tgl();
        mati();
        this.setTitle("Apotek");
        this.setLocation(dmn.width/2-this.getWidth()/2,dmn.height/2-this.getHeight()/2);
    }

    public void aidi(){
         try{
            String sql = "select max(right(IDTransaksi,3)) from transaksi";
            Statement stat = con.createStatement();
            ResultSet rs= stat.executeQuery(sql);
            while(rs.next()){
                if(rs.first()==false){
                    aidi.setText("TRS001");
                } else {
                    rs.last();
                    int aut = rs.getInt(1) + 1;
                        String nomor = String.valueOf(aut);
                        int Long = nomor.length();
                        
                        for(int a=0;a<3-Long;a++){
                            nomor = "0" + nomor;
                        }
                        aidi.setText("TRS"+nomor);
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "data gagal otomatis"+e);
        }

    }
    
    public void ngacak(){
        int angka = (int)
        (Math.random()*999999);
        det.setText(String.valueOf(angka));
    }
    
    private void mati(){
        aidi.setEnabled(false);
        aidibar.setEnabled(false);
        tanggal.setEnabled(false);
        subtot.setEnabled(false);
        total.setEnabled(false);
        kembali.setEnabled(false);
        Nama.setEnabled(false);
        harga.setEnabled(false);
    }
    
    private void sumtotal(){
        String sql = "select sum(Harga*Jumlah) from transaksi where IDTransaksi='"+aidi.getText()+"'";
        try{
                Statement stat = con.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                if(hasil.next()){
                    total.setText(hasil.getString(1));
                }else{
                }
        }catch (Exception e){
        }
    }
    
    private void filterangka (KeyEvent a){
      if(Character.isAlphabetic(a.getKeyChar())){
          a.consume();
          JOptionPane.showMessageDialog(rootPane, "Anda tidak bisa memasukan huruf !");
      }
     }
    
    public void tgl(){
        Date skrg= new Date();
        SimpleDateFormat format= new SimpleDateFormat("dd MMMM yyyy");
        tanggal.setText(format.format(skrg));
    }
    private void kosong(){
        jumlah.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        aidi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kembali = new javax.swing.JTextField();
        subtot = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        Nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        beli = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        aidibar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mencari = new javax.swing.JTextField();
        bilang = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        det = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        keluar = new javax.swing.JMenu();
        tentang = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(670, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Kembalian: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 80, -1));

        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bayarKeyTyped(evt);
            }
        });
        getContentPane().add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 130, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/button_previous_01.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        aidi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aidiActionPerformed(evt);
            }
        });
        getContentPane().add(aidi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Total: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("ID Barang: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 20));
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 130, -1));
        getContentPane().add(subtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 130, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Nama", "Jumlah", "Total"
            }
        ));
        tabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabel.setColumnSelectionAllowed(true);
        tabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabel.setDragEnabled(true);
        tabel.setInheritsPopupMenu(true);
        tabel.setMinimumSize(new java.awt.Dimension(120, 64));
        jScrollPane2.setViewportView(tabel);
        tabel.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 610, 80));
        getContentPane().add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/logo3.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 50, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Cari Barang:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Bayar: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 60, -1));

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlahKeyTyped(evt);
            }
        });
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 130, -1));

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Transaksi");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jumlah:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        beli.setText("Beli");
        beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliActionPerformed(evt);
            }
        });
        getContentPane().add(beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Sub Total: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));
        getContentPane().add(aidibar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID Transaksi: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Harga:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        mencari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencariActionPerformed(evt);
            }
        });
        mencari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mencariKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mencariKeyTyped(evt);
            }
        });
        getContentPane().add(mencari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 130, -1));

        bilang.setText("....");
        getContentPane().add(bilang, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 130, -1));
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 130, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nama Barang:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/90580cca18c50e5.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        det.setText("jTextField1");
        getContentPane().add(det, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        keluar.setText("Keluar");
        keluar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                keluarMenuSelected(evt);
            }
        });
        jMenuBar1.add(keluar);

        tentang.setText("Tentang");
        tentang.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                tentangMenuSelected(evt);
            }
        });
        jMenuBar1.add(tentang);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyReleased
        String bsr= bayar.getText();
        bilang.setText(new JavaTerbilang(bsr).toString() + " rupiah");
    }//GEN-LAST:event_bayarKeyReleased

    private void bayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyTyped
        filterangka(evt);
    }//GEN-LAST:event_bayarKeyTyped

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Penjualan trans = new Penjualan();
        trans.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void aidiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aidiActionPerformed

    }//GEN-LAST:event_aidiActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed

    }//GEN-LAST:event_jumlahActionPerformed

    private void jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyTyped
        filterangka(evt);
    }//GEN-LAST:event_jumlahKeyTyped

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        if(jumlah.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Jumlah tidak boleh kosong !");
        }else{
            int a,b,c;
            a=Integer.parseInt(harga.getText());
            b=Integer.parseInt(jumlah.getText());
            c= a*b;
            subtot.setText(""+c);


                String hrg = "insert into transaksi values (?,?,?,?,?,?)";
                try {
                    PreparedStatement stat = con.prepareStatement(hrg);
                    stat.setString(1, aidi.getText());
                    stat.setString(2, Nama.getText());
                    stat.setString(3, harga.getText());
                    stat.setString(4, tanggal.getText());
                    stat.setString(5, jumlah.getText());
                    stat.setString(6, subtot.getText());
                    stat.executeUpdate();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Data Gagal Ditambah // " +e);
                }
                
            tabel.setModel(tabMode);
            tabMode.addRow(new Object[]{
                aidi.getText(),Nama.getText(),jumlah.getText(),
                subtot.getText()
            });
            sumtotal();
            kosong();
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void keluarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_keluarMenuSelected
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_keluarMenuSelected

    private void tentangMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_tentangMenuSelected
        About about = new About();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tentangMenuSelected

    private void beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliActionPerformed
        if(bayar.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Bayar tidak boleh kosong !");
        }else{
            int a,b,c;
            a=Integer.parseInt(total.getText());
            b=Integer.parseInt(bayar.getText());
            c=b-a;
            kembali.setText(""+c);
            int bay, har;
            bay = Integer.parseInt(bayar.getText());
            har = Integer.parseInt(harga.getText());

            if(bay<har){
                JOptionPane.showMessageDialog(rootPane, "Harap bayar dengan uang pas atau lebih !");
            }else{
                
            String sql = "insert into detail values (?,?,?,?)";
                try {
                    PreparedStatement stat = con.prepareStatement(sql);
                    stat.setString(1, aidi.getText());
                    stat.setString(2, total.getText());
                    stat.setString(3, bayar.getText());
                    stat.setString(4, kembali.getText());
                    stat.executeUpdate();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Data Gagal Ditambah //" +e);
                }
            
                
                String id="";
                String sql2 = "select * from transaksi";
                try{
                    PreparedStatement stat = con.prepareStatement(sql2);
                    ResultSet rs = stat.executeQuery(sql2);
                    while(rs.next()){
                        id =rs.getString("IDTransaksi");
                    }
                }catch(Exception e){

                }

                JasperReport JasRep;
                JasperPrint JasPri;
                Map<String, Object> no = new HashMap<>();
                HashMap parameter = new HashMap();
                JasperDesign JasDes;
                try{
                   File report = new File("src/tubes/Trans.jrxml");
                   JasDes = JRXmlLoader.load(report);
                   no.clear();
                   parameter.put("trans",id);   
                   JasRep = JasperCompileManager.compileReport(JasDes);
                   JasPri = JasperFillManager.fillReport(JasRep, parameter, con);
                   JasperViewer.viewReport(JasPri, false);

               }catch(Exception e){
                   JOptionPane.showMessageDialog(null, e.getMessage());
               }
               aidi();
            }
        }
    }//GEN-LAST:event_beliActionPerformed

    private void mencariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencariActionPerformed

    }//GEN-LAST:event_mencariActionPerformed

    private void mencariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mencariKeyPressed
        int key = evt.getKeyCode();
        int stok = 0;
        if(key == KeyEvent.VK_ENTER)
        if(mencari.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Tidak bisa mencari jika kosong !");
        }else{
            try{
                Statement stat = con.createStatement();
                String search = mencari.getText();
                ResultSet rs = stat.executeQuery("SELECT * FROM barang WHERE Nama like '%"+search+"%' OR Keterangan like '%"+search+"%' AND Stok !='"+stok+"'");
               while (rs.next()) {
                   
                    aidibar.setText(rs.getString("IDBarang"));
                    Nama.setText(rs.getString("Nama"));
                    harga.setText(rs.getString("Harga"));
                
                rs.close();
                mencari.setText("");   
               
               }
            }catch (Exception e){
            }
        }
    }//GEN-LAST:event_mencariKeyPressed

    private void mencariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mencariKeyTyped

    }//GEN-LAST:event_mencariKeyTyped

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed

    }//GEN-LAST:event_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField aidi;
    private javax.swing.JTextField aidibar;
    private javax.swing.JButton back;
    private javax.swing.JTextField bayar;
    private javax.swing.JButton beli;
    private javax.swing.JLabel bilang;
    private javax.swing.JTextField det;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JMenu keluar;
    private javax.swing.JTextField kembali;
    private javax.swing.JTextField mencari;
    private javax.swing.JTextField subtot;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tanggal;
    private javax.swing.JMenu tentang;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
